import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import GradientBackground from "@/components/ui-engineer/layout/gradient-background";
import { Spotlight } from "@/components/aceternity/spotlight-new";
import { Tomorrow } from "next/font/google";
import { ContributionGraphProvider } from "@/context/cg-context";
import { MusicPlayer } from "@/components/ui-engineer/layout/music-player";
import QuickAction from "@/components/ui-engineer/layout/quick-action";
import { Toaster } from "@/components/ui/sonner";
import HiddenComponent from "@/components/ui-engineer/hidden-component";
import Script from "next/script";
import { ProfileProvider } from "@/context/profile-context";

const tomorrow = Tomorrow({
   subsets: ["latin"],
   variable: "--font-tomorrow",
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   style: ["normal", "italic"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "NV-Phong",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${tomorrow.variable} antialiased scrollbar-hide selection:bg`}
         suppressHydrationWarning
      >
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="pastel-pink"
               enableSystem
               disableTransitionOnChange
               themes={[
                  "light",
                  "dark",
                  "pastel-pink",
                  "pastel-green",
                  "pastel-blue",
                  "pastel-violet",
                  "pastel-orange",
               ]}
            >
               <ContributionGraphProvider>
                  <Spotlight />
                  <ProfileProvider>
                     {children}
                     <Toaster />
                     <HiddenComponent routes={["/resume"]}>
                        <MusicPlayer />
                     </HiddenComponent>
                  </ProfileProvider>
                  <HiddenComponent routes={["/themes/*"]}>
                     <GradientBackground />
                  </HiddenComponent>
                  <QuickAction />
               </ContributionGraphProvider>
            </ThemeProvider>
            <Analytics />
            <SpeedInsights />
            <Script
               src="https://challenges.cloudflare.com/turnstile/v0/api.js"
               async
               defer
            />
         </body>
      </html>
   );
}
