import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { MusicPlayer } from "@/components/ui-engineer/music-player";
import GradientBackground from "@/components/ui-engineer/gradient-background";
import { MagicUIDock } from "@/components/layout/magicui-dock";
import { Spotlight } from "@/components/aceternity/spotlight-new";

export const metadata: Metadata = {
  title: "NV-Phong",
  description: "Generated by NV-Phong",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scrollbar-hide selection:bg"
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="pastel-pink"
          enableSystem
          disableTransitionOnChange
          themes={["light", "dark", "pastel-pink"]}
        >
          <Spotlight />
          {children}
          <MagicUIDock />
          <MusicPlayer />
          <GradientBackground />
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
