import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/contexts/toast-context";
import { NavigationProvider } from "@/contexts/navigation-context";
import { HeaderProvider } from "@/contexts/header-context";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { SiteHeaderWrapper } from "@/components/layout/site-header-wrapper";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "UI Engineer",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
         >
            <ToastProvider>
               <NavigationProvider>
                  <HeaderProvider>
                     <SidebarProvider
                        style={
                           {
                              "--sidebar-width": "calc(var(--spacing) * 72)",
                              "--header-height": "calc(var(--spacing) * 12)",
                           } as React.CSSProperties
                        }
                     >
                        <AppSidebar variant="inset" />
                        <SidebarInset className="flex h-[calc(100svh-1rem)] flex-col overflow-hidden">
                           <div className="flex flex-1 flex-col overflow-auto">
                              <SiteHeaderWrapper />
                              <div className="flex flex-1 flex-col">
                                 {children}
                              </div>
                           </div>
                        </SidebarInset>
                     </SidebarProvider>
                  </HeaderProvider>
               </NavigationProvider>
            </ToastProvider>
         </body>
      </html>
   );
}
