import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { MagicUIDock } from "@/components/layout/magicui-dock";
import { ContributionGraphProvider } from "@/context/cg-context";

export const metadata: Metadata = {
   title: "CG-Editor",
   description: "Generated by NV-Phong",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className="scrollbar-hide selection:bg"
         suppressHydrationWarning
      >
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="light"
               enableSystem
               disableTransitionOnChange
               themes={["light", "dark", "pastel-pink"]}
            >
               <ContributionGraphProvider>
                  {children}
                  <MagicUIDock />
               </ContributionGraphProvider>
            </ThemeProvider>
         </body>
      </html>
   );
}
